// <auto-generated />
using System;
using Gevangenis.EFCoreMigrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gevangenis.EFCoreMigrations.Migrations
{
    [DbContext(typeof(PrisonContext))]
    [Migration("20220921112241_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gevangenis.Models.Entity.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIsolationCell")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrisonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrisonId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Gevangenis.Models.Entity.Prison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountPrisoners")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prisons");
                });

            modelBuilder.Entity("Gevangenis.Models.Entity.Prisoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTimeSentence")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnterPrisonDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeavePrisonDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrisonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PrisonerType")
                        .HasColumnType("prisonerType");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("PrisonId");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("Gevangenis.Models.Entity.Cell", b =>
                {
                    b.HasOne("Gevangenis.Models.Entity.Prison", "Prison")
                        .WithMany("Cells")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("Gevangenis.Models.Entity.Prisoner", b =>
                {
                    b.HasOne("Gevangenis.Models.Entity.Cell", "Cell")
                        .WithMany("Prisoners")
                        .HasForeignKey("CellId");

                    b.HasOne("Gevangenis.Models.Entity.Prison", "Prison")
                        .WithMany()
                        .HasForeignKey("PrisonId");

                    b.Navigation("Cell");

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("Gevangenis.Models.Entity.Cell", b =>
                {
                    b.Navigation("Prisoners");
                });

            modelBuilder.Entity("Gevangenis.Models.Entity.Prison", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
